import flushAllPromises from '../../testHelpers/flushAllPromises'
import { MobileEnzymeElement } from './MobileEnzymElement'

export class MobileEnzymeDriver {
  constructor (wrapper) {
    wrapper.refresh = this.refresh.bind(this)
    this.wrapper = wrapper
    return this.wrapper.refresh()
  }

  getElement (selector) {
    return new MobileEnzymeElement(this.wrapper, selector)
  }

  async refresh () {
    // TODO can we somehow make sure that we flush all the existing promises, and then also the promises
    // that are created (?) as a result of this flush?
    // otherwise we could have this in a loop that would be configurable via some kind of a threshold.
    // We could think of this similarly to a waitFor-kind timeouts in e2e testing

    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    await flushAllPromises()
    this.wrapper.update()
    this.wrapper.mount()
    return this
  }

  get html () {
    return this.wrapper.html()
  }
}
